#!/bin/bash

if [ $# -ne 1 ]; then
	echo "Usage: sphp [phpversion]"
	exit 1
fi

currentversion="`php -r \"echo str_replace('.', '', substr(phpversion(), 0, 3));\"`"
newversion="$1"

brew list php$newversion 2> /dev/null > /dev/null

if [ $? -eq 0 ]; then
	echo "PHP version $newversion found"
	
	echo "Stopping PHP-FPM $currentversion"
	launchctl unload -w ~/Library/LaunchAgents/homebrew.mxcl.php$currentversion.plist

	echo "Unlinking old binaries..."
	brew unlink php$currentversion 2> /dev/null > /dev/null

	echo "Linking new binaries..."
	brew link php$newversion

	echo "Starting PHP-FPM $currentversion"
	launchctl load -w ~/Library/LaunchAgents/homebrew.mxcl.php$newversion.plist

	echo "Restarting apache"

	pgrep -f /usr/local/opt/httpd24/bin/httpd 2> /dev/null > /dev/null
	if [ $? -eq 0 ]; then
		echo "Restarting system Apache..."
		pkill -9 -f /usr/local/opt/httpd24/bin/httpd
		/usr/local/bin/apachectl -k restart > /dev/null 2>&1
	fi
	pgrep -f /usr/local/Cellar/*/httpd 2> /dev/null > /dev/null
	if [ $? -eq 0 ]; then
		echo "Restarting homebrew Apache..."
		pkill -9 -f /usr/local/Cellar/*/httpd
		/usr/local/bin/apachectl -k restart > /dev/null 2>&1
	fi

	echo "Done."
else
	echo "PHP version $newversion was not found."
	exit 1
fi
